export { Expenses } from './Expenses'
export { Add } from './Add'
export { Reports } from './Reports'
export { Settings } from './Settings'
export {ProfileScreen} from './ProfileScreen'
export { NotificationSettings } from './NotificationSettings'
export { IncomeReport } from './IncomeReport'

export {LoginPage} from './LoginScreen'
export {Register} from './SignUp'
// export {SplashScreen} from './SplashScreen'